### PR TITLE
Piwik -> Matomo

### PR DESCRIPTION
**Pull request by Findus23**
TODO:

- [ ] update `GITHUB_REPOSITORY` after renaming the piwik repository
- [ ] update my pull request (sitemap base url)

### CODE REVIEW

**Comment by tsteur** [comment]
👍  I think this could be already merged? Feel free to complete it first though

**Comment by Findus23** [comment]
The latter is just a reminder before #11 gets merged and for the former the `matomo-org/piwik` repository will need to be renamed first.

**Comment by tsteur** [comment]
So good to merge already? or still wait?

**Comment by Findus23** [comment]
@tsteur 

I updated the repository URL and it seems to be working, so I guess this can be merged.
Obviously `src/config/config.php` also needs to be changed.

**Pull request merged**
